version: "3"
services:
  qiushaocloud-gitlab-ce-server:
    image: gitlab/gitlab-ce
    container_name: qiushaocloud-gitlab-ce-server
    hostname: qiushaocloud-gitlab-ce-server
    privileged: true
    restart: always
    ports:
      - '$GITLAB_SERVER_WEB_PORT:$NGINX_LISTEN_PORT'
      - '$GITLAB_SERVER_SSH_PORT:22'
    volumes:
      - '$GITLAB_VOLUMES_CONFIG:/etc/gitlab'
      #- '$GITLAB_VOLUMES_LOGS:/var/log/gitlab'
      - '$GITLAB_VOLUMES_DATA:/var/opt/gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '$EXTERNAL_URL'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['gitlab_ssh_host'] = '$GITLAB_RAILS_GITLAB_SSH_HOST'
        gitlab_rails['gitlab_shell_ssh_port'] = $GITLAB_RAILS_GITLAB_SHELL_SSH_PORT
        gitlab_rails['initial_root_password'] = '$GITLAB_RAIL_INITIAL_ROOT_PASSWORD'
        nginx['enable'] = true
        nginx['listen_port'] = $NGINX_LISTEN_PORT
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "Host" => "$$http_host",
          "X-Real-IP" => "$$remote_addr",
          "X-Forwarded-For" => "$$proxy_add_x_forwarded_for",
          "X-Forwarded-Proto" => "http"
        }
    networks:
      - gitlab-network

  qiushaocloud-gitlab-runner-server:
    image: gitlab/gitlab-runner
    container_name: qiushaocloud-gitlab-runner-server
    hostname: qiushaocloud-gitlab-runner-server
    privileged: true
    restart: always
    depends_on:
      - qiushaocloud-gitlab-ce-server
    volumes:
    - $GITLAB_VOLUMES_RUNNER_CONFIG:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab-network


networks:
  gitlab-network:
